#!/usr/bin/env node
/**
 * Build `dist/tokens.css` from the TypeScript token sources.
 *
 * Emits:
 *   - @font-face declarations for Noto Sans 400/500/700, Inter 600/700,
 *     JetBrains Mono 400/700. Paths point to `fonts/` (populated by
 *     `fetch-fonts.mjs`).
 *   - CSS custom properties for colour primitives, semantic tokens,
 *     typography, spacing, radii, shadow.
 *
 * Keep this script dependency-free (stdlib only). It runs during
 * `pnpm --filter @gh/gh-ds build` and in CI.
 */

import { mkdir, writeFile, stat } from 'node:fs/promises';
import { gzipSync } from 'node:zlib';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Dynamic imports from TS are handled by tsx; this file runs under Node ≥22
// with --experimental-strip-types, or via tsx at build time.
import { colour, colourFlat } from '../src/tokens/colour.ts';
import { semantic } from '../src/tokens/semantic.ts';
import {
  fontFamily,
  fontWeight,
  fontSize,
  lineHeight,
} from '../src/tokens/typography.ts';
import { spacing, radius, borderWidth, shadow } from '../src/tokens/spacing.ts';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const distDir = join(root, 'dist');

const NOTO_SANS_WEIGHTS = [400, 500, 700];
const INTER_WEIGHTS = [600, 700];
const JETBRAINS_WEIGHTS = [400, 700];

const BUDGET_BYTES_GZIP = 4 * 1024; // 4 KB per week-0.md §4 PR 2 DoD

/**
 * Consumers of tokens.css are expected to serve the matching WOFF2 files at
 * `/fonts/<family>-<weight>.woff2` on their origin. The `apps/portal` build
 * copies the WOFF2s from `packages/gh-ds/fonts/` into `public/fonts/` during
 * its prebuild step so Astro ships them at that absolute path.
 */
function fontFaces() {
  const faces = [];
  for (const weight of NOTO_SANS_WEIGHTS) {
    faces.push(`@font-face {
  font-family: 'Noto Sans';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/noto-sans-${weight}.woff2') format('woff2');
}`);
  }
  for (const weight of INTER_WEIGHTS) {
    faces.push(`@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/inter-${weight}.woff2') format('woff2');
}`);
  }
  for (const weight of JETBRAINS_WEIGHTS) {
    faces.push(`@font-face {
  font-family: 'JetBrains Mono';
  font-style: normal;
  font-weight: ${weight};
  font-display: swap;
  src: url('/fonts/jetbrains-mono-${weight}.woff2') format('woff2');
}`);
  }
  return faces.join('\n');
}

function colourCustomProps() {
  const lines = [];
  for (const [scale, steps] of Object.entries(colour)) {
    for (const [step, hex] of Object.entries(steps)) {
      lines.push(`  --${scale}-${step}: ${hex};`);
    }
  }
  return lines.join('\n');
}

function semanticCustomProps() {
  const lines = [];
  for (const [name, value] of Object.entries(semantic)) {
    lines.push(`  --color-${name}: ${value};`);
  }
  return lines.join('\n');
}

function typeCustomProps() {
  const lines = [
    `  --font-body: ${fontFamily.body};`,
    `  --font-display: ${fontFamily.display};`,
    `  --font-mono: ${fontFamily.mono};`,
  ];
  for (const [name, weight] of Object.entries(fontWeight)) {
    lines.push(`  --font-weight-${name}: ${weight};`);
  }
  for (const [name, size] of Object.entries(fontSize)) {
    lines.push(`  --font-size-${name}: ${size};`);
  }
  for (const [name, leading] of Object.entries(lineHeight)) {
    lines.push(`  --line-height-${name}: ${leading};`);
  }
  return lines.join('\n');
}

function spacingCustomProps() {
  const lines = [];
  for (const [name, value] of Object.entries(spacing)) {
    lines.push(`  --space-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(radius)) {
    lines.push(`  --radius-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(borderWidth)) {
    lines.push(`  --border-width-${name}: ${value};`);
  }
  for (const [name, value] of Object.entries(shadow)) {
    lines.push(`  --shadow-${name}: ${value};`);
  }
  return lines.join('\n');
}

const css = `/*
 * @gh/gh-ds tokens — generated by scripts/build-css.mjs
 * Do not edit directly. Change the TypeScript source under src/tokens/.
 *
 * Source of truth: .claude/CLAUDE.md §6.1 (colour) and §6.2 (typography).
 * ADR-003 documents the GOV.UK Frontend fork decision.
 */

${fontFaces()}

:root {
  /* Colour primitives — use semantic tokens below, not these directly. */
${colourCustomProps()}

  /* Semantic tokens — consume these in components. */
${semanticCustomProps()}

  /* Typography. */
${typeCustomProps()}

  /* Spacing, radii, borders, shadow. */
${spacingCustomProps()}
}

@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
`;

await mkdir(distDir, { recursive: true });
const outputPath = join(distDir, 'tokens.css');
await writeFile(outputPath, css, 'utf8');

const rawSize = Buffer.byteLength(css, 'utf8');
const gzipSize = gzipSync(css).length;

// eslint-disable-next-line no-console
console.log(`@gh/gh-ds: wrote dist/tokens.css
  raw:      ${rawSize} bytes
  gzipped:  ${gzipSize} bytes  (budget: ${BUDGET_BYTES_GZIP} bytes)`);

// Silence the "never used" lint from colourFlat at import time. Kept imported
// so the generator is still loaded when CSS output changes to inline values.
void colourFlat;

if (gzipSize > BUDGET_BYTES_GZIP) {
  // eslint-disable-next-line no-console
  console.error(
    `\n❌ tokens.css exceeds 4 KB gzipped budget (was ${gzipSize} bytes). ` +
      `Remove tokens or compress values before merging.`,
  );
  process.exit(1);
}

// Sanity: confirm the file we just wrote matches the size we measured.
const written = await stat(outputPath);
if (written.size !== rawSize) {
  // eslint-disable-next-line no-console
  console.error(
    `size mismatch after write: expected ${rawSize} bytes, on-disk ${written.size}`,
  );
  process.exit(1);
}
