#!/usr/bin/env node
/**
 * Emit `CONTRAST-REPORT.md` from the current semantic-token mapping.
 *
 * Runs the same WCAG-2.2 math the test suite does, and prints a human-readable
 * table documenting every text-on-surface check, every UI-adjacent check,
 * and the focus-ring-on-action-primary check. Known exemptions (e.g.
 * `border-default` per GOV.UK pattern) are flagged explicitly.
 *
 * Designed for reviewers and auditors, not for humans to hand-edit. The file
 * is regenerated by `pnpm --filter @gh/gh-ds report:contrast` and committed
 * as part of the PR that changes any token.
 */

import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  semantic,
  textOnSurfaceTokens,
  uiAdjacentTokens,
} from '../src/tokens/semantic.ts';
import { colourFlat } from '../src/tokens/colour.ts';
import { checkContrast, formatRatio } from '../src/contrast.ts';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'CONTRAST-REPORT.md');

const SURFACE = colourFlat['ghana-ink-50'];
const DARK_SURFACE = colourFlat['ghana-ink-900'];

function row(token, fg, bg, requiredRatio) {
  const r = checkContrast(fg, bg);
  const verdict = r.ratio >= requiredRatio ? '✅ pass' : '❌ fail';
  return `| \`${token}\` | \`${fg}\` | \`${bg}\` | ${formatRatio(r.ratio)} | ${requiredRatio}:1 | ${verdict} |`;
}

const now = new Date().toISOString().slice(0, 10);

const textRows = textOnSurfaceTokens
  .map((t) => row(t, semantic[t], SURFACE, 4.5))
  .join('\n');

const uiRows = uiAdjacentTokens.map((t) => row(t, semantic[t], SURFACE, 3)).join('\n');

// Special: focus-ring against action-primary (its intended adjacent surface).
const focusRow = row('focus-ring', semantic['focus-ring'], semantic['action-primary'], 3);

// Special: warning-text on warning-bg composite.
const warningRow = row(
  'warning-text',
  semantic['warning-text'],
  semantic['warning-bg'],
  4.5,
);

// Known-gap table — texts on dark surface, flagged for a later dark-mode PR.
const darkRows = textOnSurfaceTokens
  .map((t) => row(t, semantic[t], DARK_SURFACE, 4.5))
  .join('\n');

const doc = `# Ghana Design System — contrast report

_Generated: ${now} by \`pnpm --filter @gh/gh-ds report:contrast\`._
_Source of truth: \`.claude/CLAUDE.md §6.1\` and \`src/tokens/semantic.ts\`._

WCAG 2.2 SC 1.4.3 requires 4.5:1 for normal text. SC 1.4.11 requires 3:1 for
meaning-bearing non-text UI. This report runs every semantic token through the
relative-luminance formula in \`src/contrast.ts\` and records the measured
ratio.

## Text on surface (\`ghana-ink-50\`) — must meet 4.5:1

| Token | Foreground | Background | Ratio | Required | Verdict |
| ----- | ---------- | ---------- | ----- | -------- | ------- |
${textRows}

## UI-adjacent tokens on surface — must meet 3:1

| Token | Foreground | Background | Ratio | Required | Verdict |
| ----- | ---------- | ---------- | ----- | -------- | ------- |
${uiRows}

## Composite-component checks

| Token | Foreground | Background | Ratio | Required | Verdict |
| ----- | ---------- | ---------- | ----- | -------- | ------- |
${focusRow}
${warningRow}

## Known exemptions

- **\`border-default\` (\`#B1B4B6\` on surface).** Does not meet 3:1 in
  isolation. Permitted under the GOV.UK Frontend composite-component pattern:
  form-control identity is conveyed by the full component (label, hint text,
  focus ring, error state), so the border edge itself is decorative rather
  than meaning-bearing. Matches \`govuk-border-colour\` behaviour in the
  audited upstream. Any component that renders \`border-default\` must also
  render at least one 4.5:1-contrast element within the component bounds
  (label or value text).

## Dark-mode follow-up (not yet shipped)

These tokens are intentionally light-mode only. The table below records
known failures for future work — a dark-mode variant must replace each
failing row before dark mode ships.

| Token | Foreground | Background | Ratio | Required | Verdict |
| ----- | ---------- | ---------- | ----- | -------- | ------- |
${darkRows}

## Update policy

- Re-run \`pnpm --filter @gh/gh-ds report:contrast\` in every PR that touches
  \`src/tokens/semantic.ts\` or \`src/tokens/colour.ts\`.
- Every ❌ in the two top tables is a merge blocker.
- Exemptions move into the "Known exemptions" section with a cited reason.
- Dark-mode gaps are tracked here until resolved by a dark-mode token PR.
`;

await writeFile(outPath, doc, 'utf8');
// eslint-disable-next-line no-console
console.log(`@gh/gh-ds: wrote ${outPath}`);
