/**
 * @gh/gh-ds — Ghana Design System.
 *
 * Public entry point. Consumers import tokens from here.
 *
 *   import { semantic, fontFamily } from '@gh/gh-ds';
 *
 * CSS custom properties are generated by `scripts/build-css.mjs` and ship
 * as `dist/tokens.css`. Astro apps `@import` that file once per site.
 */

export * from './tokens/index.ts';
