name = "gov-gh-design-system"
compatibility_date = "2026-04-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[env.staging]
vars = { ENVIRONMENT = "staging" }

[env.production]
vars = { ENVIRONMENT = "production" }

[observability]
enabled = true
head_sampling_rate = 1
